### ISSUE TITLE
 ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'testOrClassName' because it is an empty string.

### ISSUE THREAD

**Issue by trisapeace** [ricardoserradas/RuntSQLtTests-AzDO#12]
Duplicate of #11 (but GitHub wouldn't let me comment on a Closed issue).

I have the same problem in my pipelines when I have the "Run all test suites and test cases" checkbox checked.

To fix it, I did the following:
* Unchecked the "Run all test suites and test cases" checkbox
* Added something into the "The name of the Test Class or Test Case you want to run" field
* Saved
* Checked the "Run all test suites and test cases" checkbox, leaving the value in the "The name of the Test Class or Test Case you want to run" field
* Re-ran my pipeline

My guess is because it's marked as a required parameter and it is still counting as a required parameter even though the checkbox hides it. Not sure if this is a bug in this plugin's configuration or if it's an Azure DevOps problem.

**Comment by Waylon58** [comment]
I also encountered this error and worked around it using the steps @trisapeace provided.

**Comment by riserrad** [comment]
Once again, thank you @Waylon58 ! Code adjusted (there was a conflict to solve with your other PR) and merged!
