### ISSUE TITLE
Task not failing on failed tests

### ISSUE THREAD

**Issue by petrce** [ricardoserradas/RuntSQLtTests-AzDO#25]
@riserrad please how can I please force the task to fail when there are failing unit tests?
thanks

**Comment by riserrad** [comment]
Hi @petrce - not sure if you're using YAML to configure your pipeline, but here's how to do it:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml#yaml-snippet

You must set `failTaskOnFailedTests` to `true`

**Comment by petrce** [comment]
thanks a lot, this is a checkbox on old builds:
![image](https://user-images.githubusercontent.com/600185/106723371-f3b8b880-65fe-11eb-989e-6d04787fd316.png)

btw if you are in process of fixing the tests, and you want the build to fail only when you introduce new failing tests,
I am using this short PowerShell task script:
( https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops )
```
$testsResult = Get-Content "$env:System_DefaultWorkingDirectory/tSQLt-out/TEST-Results.xml"
$maxFailingTests = 4

$matches = ([regex]'<failure').Matches($testsResult);
$testsFailed = $matches.Count

if ($testsFailed -gt $maxFailingTests)
{
    Write-Error "$testsFailed tests failed"
}
```
