### ISSUE TITLE
1. Ability to run the individual test class/ test suite

### ISSUE THREAD

**Issue by v-rajpul** [ricardoserradas/RuntSQLtTests-AzDO#6]
In PR and CI build we want to run the BVT (Build verification Tests) and we don't want to run all the test classes.

**Comment by riserrad** [comment]
Hi @v-rajpul.

I'm happy to tell you that I could implement this enhancement and it's already available to you on the build task.

Keep sharing such valuable feedbacks for improving this to the community.

Thanks!

**Comment by v-rajpul** [comment]
@ricardoserradas Thanks a lot for implementing this. I Will test this Monday (04/08) and update here.
