### ISSUE TITLE
Code coverage results for all the objects in SQL

### ISSUE THREAD

**Issue by v-rajpul** [ricardoserradas/RuntSQLtTests-AzDO#8]
Currently it is only showing the code coverage results for Stored Procedures and we want to see the code coverage results for all the objects in SQL like tables, constraints, triggers etc.

**Comment by riserrad** [comment]
Hi @v-rajpul.

I understand and share your wish to extend code coverage for other objects within a SQL Database.

This extension relies on the [SQL Cover](https://github.com/GoEddie/SQLCover#3-cover-anything-else) tool, which process code coverage only for SQL Statements. This means that only pieces of code like procedures and functions - if having some statements within - will be covered.

As a suggestion, if you want to check if a table, constraint or other object is working properly, you can write a validation procedure to it and then covering it with a Unit Test.

For more information, I'm sharing this link:

https://the.agilesql.club/2016/04/sqlcover-code-coverage-for-sql-server-t-sql/

**Comment by riserrad** [comment]
For example, you can leverage these utilities inside tSQLt to test some "validation" procedure:

https://tsqlt.org/user-guide/isolating-dependencies/applyconstraint/
